name: Run PQG Null Test

on:
  workflow_dispatch:

jobs:
  nulltest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gliccser/pqg:latest

    steps:
      - name: Run null_test.py
        run: python3 null_test.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: nulltest-results
          path: summary_null.txt
