name: Run PQG Null Test

on:
  workflow_dispatch:

jobs:
  run-nulltest:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker availability
        run: docker --version

      - name: Pull PQG Docker image
        run: docker pull ghcr.io/gliccser/pqg:latest

      - name: Run null_test.py
        run: docker run ghcr.io/gliccser/pqg:latest python3 null_test.py
